<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="NamTH2-PC2" name="order.createOrder.CreateOrderFromShop_NotLogin_COD" tests="1" failures="0" timestamp="20 Jun 2017 04:46:02 GMT" time="31.691" errors="1">
  <testcase name="CO002_VerifyInfoWhenOrderFromShop_NotLogin_COD" time="31.691" classname="order.createOrder.CreateOrderFromShop_NotLogin_COD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at actions.ActionGenWeb.waitForPageLoad(ActionGenWeb.java:204)
	at actions.ActionGenWeb.click(ActionGenWeb.java:98)
	at main.actions.Action.addNewRecipient_checkoutpage(Action.java:305)
	at main.actions.Action.checkout(Action.java:377)
	at main.actions.Action.createOrderFromShop(Action.java:835)
	at order.createOrder.CreateOrderFromShop_NotLogin_COD.CO002_VerifyInfoWhenOrderFromShop_NotLogin_COD(CreateOrderFromShop_NotLogin_COD.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- CO002_VerifyInfoWhenOrderFromShop_NotLogin_COD -->
</testsuite> <!-- order.createOrder.CreateOrderFromShop_NotLogin_COD -->
